[project]
name = 'task-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.task-bidding]
path = 'contracts/task-bidding.clar'
[contracts.Task-creation]
path = 'contracts/Task-creation.clar' 
clarity_version = 3
epoch = 3.0

[contracts.escrow-payment]
path = 'contracts/escrow-payment.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
